[project]
name = "lollipop"
version = "0.1.1"
description = " ðŸ­ Embed your videos inside of Subtitles/Captions (HELL YEAH) "
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "numpy>=2.3.1",
    "opencv-python>=4.11.0.86",
    "pycaption>=2.2.16",
]
